### ISSUE TITLE
Quality gets lowered for sjpg

### ISSUE THREAD

**Issue by beckmx** [lvgl/lv_lib_split_jpg#11]
hello guys, I have a doubt with one JPG image, if I load the C-array from the "small image" I can see it in the screen, but looks the colors are lowered in quality. To make a test, I tried to load a normal jpg as C-array but doesnt load, just gives me the no-data message, if I convert it to sjpg, it does load, but also as in the example the quality gets lowered, I already tried with the png decoder and works good with a minor detail but loads, could it be the format of my jpg image?

**Comment by vinodstanur** [comment]
Actually the python sjpg converting script takes the jpg as input and do a 90% quality on top of it. Might be the due to this reason the quality is getting a bit compromised. You can try changing the quality by modifying the line no 57 in converter script but when we keep higher value the conversion somehow takes more time. Will try some fix for this soon. 
 By the way, I hope you are not comparing the image between 24bit and 16bit, say if you open jpeg in pc and open it via lvgl in 16bit mode, you may find difference. I hope this is not the case here.
